version: '3.8'

services:
  django_app:
    container_name: django_app
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    image: django_app:latest
    restart: always
    ports:
      - "80:8000"
