version: '3.8'

services:
  django_app:
    container_name: django_app
    image: django_app:latest
    restart: always

  django_nginx:
    container_name: django_nginx
    restart: always
    image: django_nginx
    ports:
        - "80:80"